Test deploy with flynn #18.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -28,10 +28,9 @@ jobs:
           command: |
             if ! [[ "$(flynn cluster | grep "${FLYNN_CLUSTER_NAME}")" ]];
             then
-                flynn cluster add -f --no-git --docker -d -p ${FLYNN_TLS_PIN} ${FLYNN_CLUSTER_NAME} ${FLYNN_CONTROLLER_URL} ${FLYNN_CONTROLLER_KEY};
+                flynn cluster add -f --no-git --docker -d -p ${FLYNN_TLS_PIN} ${FLYNN_CLUSTER_NAME} ${FLYNN_CONTROLLER_URL} ${FLYNN_CONTROLLER_KEY}; || echo "Cert not found, copy it"
             fi;
 
-            flynn docker login || echo "Cert not found, copy it"
             export DOCKER_CA_DIR=/etc/docker/certs.d/docker.${FLYNN_CONTROLLER_URL}
             sudo mkdir -p $DOCKER_CA_DIR
             sudo cp ~/.flynn/ca-certs/default.pem ${DOCKER_CA_DIR}/ca.crt
